# -*- coding: utf-8 -*-
"""FakeNewsDetectionEMAG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u0cSPeAAQ-BpdthyI2cFyxwdXKsyjXef

# Pobieranie danych
"""

print("Hello World")

